Equips/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.SnippetDetailView.as_view(), name='detail'),
]

InventoryManagement/urls.py
from django.contrib import admin

from django.urls import path
from django.contrib.auth import views as auth_views


from userauth import views as account_views

from django.urls import path, include


urlpatterns = [
    path('', account_views.home, name='home'),
    path('home/', account_views.home, name='home'),
    path('signup/', account_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.index, name='poll_index'),
	path('book/<int:room_id>', views.bookScreen,
	 name='book_screen'),
	path('deleteAll', views.clearAllBookings, name='clrAllBookings'),
	path('book/all', views.allBookings, name="allBookings"),
	path('book/cancel/<int:booking_id>', views.cancelBooking, name="cancelBooking")
]

Equips/models.py
from django.db import models
from django.utils.timezone import now
# Create your models here.


class Equipment(models.Model):
    index = models.IntegerField(primary_key=True)
    equip_type = models.CharField(max_length=200)
    actual_equipment = models.CharField(max_length=100)
    status = models.CharField(max_length=1, default='+')
    issued_to = models.CharField(max_length=50, blank=True, null=True)
    lastIssued = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.equip_type + "_" + self.actual_equipment + "_" + str(self.index)


#
# class Room(models.Model):
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

polls/models.py
from django.db import models

# Create your models here.

class RoomResource(models.Model):
	s_no = models.CharField('Ref No.',max_length = 50)
	# name
	desc = models.CharField(max_length = 100)
	#location
	location = models.CharField(max_length = 100)

	def __str__(self):
		return self.desc

# Can be accessed in RoomResource by using command 
# RoomResource.roombooking_set object!
class RoomBooking(models.Model):
	room = models.ForeignKey(RoomResource, on_delete = models.CASCADE, null=False )
	start_time = models.DateTimeField('Start of booking', null=False)
	end_time = models.DateTimeField('End of Booking', null = False)
	roll_no = models.CharField(max_length = 20, default = 'Admin')
	active = models.BooleanField(default=True)

	def __str__(self):
		return (self.room.desc + ', by: ' 
			+ self.roll_no + ' @ ' + self.start_time.strftime("%s %s" % ("%Y-%m-%d", "%H:%M"))
			+ ', till: ' + self.end_time.strftime("%s %s" % ("%Y-%m-%d", "%H:%M")))

	def getDesc(self):
		return self.room.desc

userauth/models.py
from django.db import models

# Create your models here.

userauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomSignUpForm(UserCreationForm):
    email = forms.CharField(max_length=255, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

Equips/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from .models import Equipment
from django.views import View
from django.views.generic import ListView, DetailView

polls/views.py
# https://docs.djangoproject.com/en/3.0/topics/db/queries/
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from django.template import loader
from django.shortcuts import render
from django.utils.dateparse import parse_datetime
from datetime import datetime, timedelta, tzinfo
from django.urls import reverse

from .models import RoomResource, RoomBooking

# Create your views here.
def index(request):
	all_rooms_list = RoomResource.objects.order_by('id')


	context = {
		'all_rooms_list': all_rooms_list,
		'head_title': 'Rooms!'
	}

	return render(request, 'polls/index.html', context)

# need a room as context. 
def bookScreen(request, room_id):
	room = get_object_or_404(RoomResource, id=room_id)
	errormsg = None
	try:
		req_rno = request.POST['rno']
		req_stt = request.POST['start_tm']
	# see if post values are there. If not, render 
	# basic page
	except:
		req_rno = None
		return render(request, 'polls/book.html', 
		{'room':room, 'head_title':'Room Book'})
	else:
		try:
			begin = parse_datetime(req_stt)
		except:
			errormsg = "Enter Valid DateTime!"	
			return render(request, 'polls/book.html', 
			{'room':room, 'head_title':'Room Book', 
			'errormsg': errormsg})
		else:
			if(begin is None):
				errormsg = "Enter Valid DateTime!"	
				return render(request, 'polls/book.html', 
				{'room':room, 'head_title':'Room Book', 
				 'errormsg': errormsg})			
			else:
				end = begin + timedelta(minutes=59)
				thisbook = RoomBooking(room=room, start_time=begin, end_time=end, roll_no=req_rno)
				# thisbook.save()
				# Do it later after some checks
				
				# room_id === foreign-key.id
				querySet = RoomBooking.objects.filter(room_id = room.id).filter(
						end_time__gte=thisbook.start_time,
						start_time__lte=thisbook.end_time,
						active__exact=True,
					)

				if querySet.count()==0:
					thisbook.save()
					return render(request, 'polls/book.html', 
					{'room':room, 'head_title':'Room Book', 
					'booking_info': thisbook})
				else:
					return render(request, 'polls/book.html', 
					{'room':room, 'head_title':'Room Book', 
				 	'errormsg': 'This slot is already booked!'})	

def clearAllBookings(request):
	RoomBooking.objects.all().delete()
	return HttpResponse('Deleted all. ')

def allBookings(request):
	all_rooms_list = RoomBooking.objects.filter(active__exact=True, end_time__gte=datetime.now()).order_by('-start_time')

	context = {
		'all_rooms_list': all_rooms_list,
		'head_title': 'Rooms Bookings'
	}

	return render(request, 'polls/allBookings.html', context)

def cancelBooking(request, booking_id):
	booking = get_object_or_404(RoomBooking, id=booking_id)
	
	if (request.user.is_authenticated and request.user.email == booking.roll_no):
		booking.active=False
		booking.save()

	return HttpResponseRedirect(reverse('polls:allBookings'))

userauth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from .forms import CustomSignUpForm
# Create your views here.


def home(request):
    return render(request, 'home.html')

def signup(request):
    if request.method == 'POST':
        form = CustomSignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = CustomSignUpForm()
    return render(request, 'signup.html', {'form': form})

polls/templates/polls/allbookings.html
{% extends "base.html" %}
{% block content %}

	<h1> All bookings  </h1>
 
	<div>
			{% for room in all_rooms_list %}
			<li> 
				<strong>Room: {{ room.getDesc }} </strong>, Booked from: {{room.start_time}}, till: {{room.end_time}}, by : {{room.roll_no}} 
				{% if user.email == room.roll_no %}
					<a href="{% url 'polls:cancelBooking' room.id %}"> <strong> Cancel Booking  </strong></a>
				{% endif %}
			</li>
			{% endfor %}
	</div>

	<br>
	<div>
		{% if errormsg %} <p> <strong> Error: {{errormsg}} </strong> </p>
		{% endif %}

		{% if booking_info %}
		Booking Done!
		{{booking_info}}

		{% endif %}
	</div>
{% endblock %}

polls/templates/polls/book.html
{% extends "base.html" %}
{% block content %}

	<h1> Booking: {{room}}  </h1>
 
	<div>
		<form action="{% url 'polls:book_screen' room.id %}" method="post">
			{% csrf_token %}

			<label> Your email: </label>
			<label> {{user.email}} </label>
			<br>
			<input type="hidden" value="{{user.email}}" name="rno" />
			<label> Please enter Booking Start Time 
			in this format 'YYYY-MM-DD HH:MM'
			</label><br>
			<input type="text" name="start_tm">
			<br><br>
			<input type="submit" value="Book">
		</form>
	</div>

	<br>
	<div>
		{% if errormsg %} <p> <strong> Error: {{errormsg}} </strong> </p>
		{% endif %}

		{% if booking_info %}
		Booking Done!
		{{booking_info}}

		{% endif %}
	</div>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}
{% block content %}

	<h1> List of Rooms </h1>

	{% if all_rooms_list %}
		<ul>
			{% for room in all_rooms_list %}
			<li> 
				{{room.desc}} 
				Click <a href="{% url 'polls:book_screen' room.id %}"> here to book </a>
			</li>
			{% endfor %}
		</ul>
	{% else %}
		<p> No rooms available to show! </p>
	{% endif %}	

{% endblock %}

polls/templates/polls/struct.html
<!DOCTYPE html>
<html>
<head>
	<title> 
	{% if head_title %} {{head_title}}
	{% else %} No Title :3
	{% endif %}
	</title>
</head>

<body>
	<header>
		<div style="background-color: rgba(150,150,100,0.5);">
			<p> Welcome! </p>
		</div>
		<hr />
	</header>
	{% block content %}{% endblock %}
</body>

</html>

templates/accounts.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<div class="container">
    <h1 class="text-center logo my-4">
        <a href="{% url 'home' %}">IITH Inventory</a>
    </h1>
    {% block content %}
    {% endblock %}
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Inventory Management{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block stylesheet %}{% endblock %}
</head>

<body>
    {% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">IITH Inventory</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}

            <a href="{% url 'logout' %}" class="btn btn-outline-secondary">Logout</a>
            {% else %}

            <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
            </form>
            {% endif %}
        </div>
        </div>
    </nav>

    <div class="container">
        <ol class="breadcrumb my-4">
            {% block breadcrumb %}
            {% endblock %}
        </ol>
            {% if user.is_authenticated %}
            <h2>Welcome {{user.username}} </h2>
            {%endif%}
            <hr>

        {% if user.is_authenticated %}
        {% block content %}
        
        
        {% endblock %}
        {% else %}

        <p> Please login! </p>

        {% endif %}
    </div>
    {% endblock body %}

</body>

</html>

templates/home.html
{% extends "base.html" %}
{% block content %}

	<h1> {{room}} </h1>

	<div>
		<ul> 
			<li> <a href="{% url 'polls:poll_index' %}"> Book Rooms</a> </li>
			<li> <a href="{% url 'polls:allBookings' %}"> View all bookings </a> </li>

		</ul>
	</div>


{% endblock %}

templates/login.html
{% extends 'accounts.html' %}

{% load static %}



{% block body %}
<div class="container">
    <h1 class="text-center logo my-4">
        <a href="{% url 'home' %}">IITH Inventory</a>
    </h1>
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Log in</h3>
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-block">Log in</button>
                    </form>
                </div>
                <div class="card-footer text-muted text-center">
                    Don't have an account? <a href="{% url 'signup' %}">Sign up</a>
                </div>
            </div>
            <div class="text-center py-2">
                <small>
                    <a href="#" class="text-muted">Forgot your password?</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends 'accounts.html' %}

{% block body %}
<h2>Sign up</h2>
<div class="container">
    <h2>Sign up</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create an account</button>
    </form>
</div>
{% endblock %}  